### ISSUE TITLE
Fix upsert handling

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/axis-api#2]
Failure handling.

**Comment by ryan-kingstone** [comment]
Fix redundant upsert code in save.js
and
Add error handler for save upsert

**Comment by Rohansi** [comment]
* Switch to GridFS to support saves larger than 16MB
* Support multiple saves with versions eventually

**Comment by andrewmcwatters** [comment]
:+1: Thanks!

**Comment by andrewmcwatters** [comment]
Split @Rohansi's comment into #3, which will be addressed during the game save -> cloud save update.

**Comment by andrewmcwatters** [comment]
Closing this for now.
